### ISSUE TITLE
Solution for rendering inline math

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/dash-mp-components#5]
It would be useful to be able to render math inline with text.

Some options include [dash-katex](https://github.com/xhlulu/dash-katex) (not actively maintained?), or loading KaTeX or MathJax for the entire page (but this would not play as nicely with React).

A better option might be to fork [dcc.Markdown](https://github.com/plotly/dash-core-components/blob/dev/src/components/Markdown.react.js) (see also [here](https://github.com/plotly/dash-core-components/blob/dev/src/fragments/Markdown.react.js)) to include the [remark-math](https://github.com/Rokt33r/remark-math) plugin (see [thread](https://github.com/rexxars/react-markdown/issues/10)), and potentially submitting a PR to dash-core-components if they're interested in adopting the feature.

**Comment by mkhorton** [comment]
Second question is choice of KaTeX vs MathJax. I haven't had time to research in-depth, I'm aware KaTeX is generally faster but perhaps less feature complete. The major distinction for me would be if one supports custom fonts, or math fonts that would more neatly match with the rest of the website.

**Comment by mkhorton** [comment]
Font comparison: https://checkmyworking.com/misc/MathJax-play-area/

**Comment by codytodonnell** [comment]
See new `Markdown` component implemented in mp-react-components: https://github.com/materialsproject/mp-react-components/pull/477
