### ISSUE TITLE
Merge in latest changes from component template

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/dash-mp-components#8]
See https://github.com/plotly/dash-component-boilerplate/tree/master/%7B%7Bcookiecutter.project_shortname%7D%7D

It's likely there have been new improvements to the template since this repo was first created, specifically looking at the `package.json` and possibly the `__init__.py` too. It would be one potential source of bugs to remove.

**Comment by codytodonnell** [comment]
After comparing both `package.json` and `__init__.py` only one change needed to be made to `__init__.py`. This change was added by 57c01152d2bea8ee88fee98b1d24972b0d6ad9b9 and it fixes the `unexpected character` error in the `min.js.map` file.

**Comment by mkhorton** [comment]
I'm pretty sure there was a change required in `package.json` too for the build scripts (e.g. to build julia components)

**Comment by codytodonnell** [comment]
Are you referring to this change? https://github.com/plotly/dash-component-boilerplate/blob/master/%7B%7Bcookiecutter.project_shortname%7D%7D/package.json#L21

The only difference I'm seeing is the flag for `--jl-prefix`. Do we need to add this in?

**Comment by mkhorton** [comment]
Yeah, I think that's it. To clarify, the reason I want to stay in-sync with the cookiecutter is not because e.g. Julia integration is important for us right now, but rather to catch issues earlier if our code is not compatible with the latest features in the pipeline.
